#
# Software Name : free5gc-kubernetes
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at https://github.com/Orange-OpenSource/free5gc-kubernetes/blob/main/LICENSE
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
{{- with .Values.pcf }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "free5gc-pcf.fullname" $ }}-{{ .name }}
  labels:
    {{- include "free5gc-pcf.labels" $ | nindent 4 }}
    project: {{ $.Values.global.projectName }}
    nf: {{ .name }}
spec:
  {{- if not .autoscaling.enabled }}
  replicas: {{ .replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "free5gc-pcf.selectorLabels" $ | nindent 6 }}
      project: {{ $.Values.global.projectName }}
      nf: {{ .name }}
  template:
    metadata:
      annotations:
        {{- include "free5gc-pcf.pcfAnnotations" $ | nindent 8 }}
        checksum/config: {{ include (print $.Template.BasePath "/pcf-configmap.yaml") $ | sha256sum }}
      labels:
        {{- include "free5gc-pcf.selectorLabels" $ | nindent 8 }}
        project: {{ $.Values.global.projectName }}
        nf: {{ .name }}
    spec:
      imagePullSecrets:
        {{- toYaml .imagePullSecrets | nindent 8 }}
      securityContext:
        {{- toYaml .podSecurityContext | nindent 8 }}
      hostAliases: 
        {{- toYaml $.Values.hostAliases | nindent 8 }}
      initContainers:
      - name: wait-nrf
        {{- with $.Values.initcontainers.curl }}
        image: {{ .registry }}/{{ .image }}:{{ .tag }}
        {{- end }}
        env:
        - name: DEPENDENCIES
          value: {{ $.Values.global.sbi.scheme }}://{{ $.Values.global.nrf.service.name }}:{{ $.Values.global.nrf.service.port }}
        command: ['sh', '-c', 'set -x; for dependency in $DEPENDENCIES; do while [ $(curl --insecure --connect-timeout 1 -s -o /dev/null -w "%{http_code}" $dependency) -ne 200 ]; do echo waiting for dependencies; sleep 1; done; done;']


      containers:
      - name: database
        image: {{ $.Values.database.image }}
        ports:
          - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: {{ $.Values.database.env.POSTGRES_PASSWORD }}
      - name: acapy
        image: {{ $.Values.acapy.image }}
        env:
        - name: ACAPY_ADMIN_INSECURE_MODE
          value: "{{ $.Values.acapy.env.ACAPY_ADMIN_INSECURE_MODE }}"
        - name: ACAPY_AUTO_PROVISION
          value: "{{ $.Values.acapy.env.ACAPY_AUTO_PROVISION }}"
        - name: ACAPY_DEBUG_CONNECTIONS
          value: "{{ $.Values.acapy.env.ACAPY_DEBUG_CONNECTIONS }}"
        - name: ACAPY_ENDPOINT
          value: "{{ $.Values.acapy.env.ACAPY_ENDPOINT }}"
        - name: ACAPY_LABEL
          value: "{{ $.Values.acapy.env.ACAPY_LABEL }}"
        - name: ACAPY_LOG_LEVEL
          value: "{{ $.Values.acapy.env.ACAPY_LOG_LEVEL }}"
        - name: ACAPY_GENESIS_URL
          value: "{{ $.Values.acapy.env.ACAPY_GENESIS_URL }}"
        - name: ADMIN_PORT
          value: "{{ $.Values.acapy.env.ADMIN_PORT }}"
        - name: AGENT_PORT
          value: "{{ $.Values.acapy.env.AGENT_PORT }}"
        - name: ISSUER_DID
          value: "{{ $.Values.acapy.env.ISSUER_DID }}"
        - name: SCHEMA_ID
          value: "{{ $.Values.acapy.env.SCHEMA_ID }}"
        - name: CRED_DEF_ID
          value: "{{ $.Values.acapy.env.CRED_DEF_ID }}"
        command:
          - "/bin/bash"
          - "-c"
          - >
            aca-py start \
              --admin '0.0.0.0' {{ $.Values.acapy.env.ADMIN_PORT }} \
              --inbound-transport http '0.0.0.0' {{ $.Values.acapy.env.AGENT_PORT }} \
              --webhook-url 'http://localhost:9999/webhooks' \
              --outbound-transport http \
              --wallet-type askar \
              --wallet-name tub-wallet \
              --wallet-key tub-key \
              --preserve-exchange-records \
              --auto-provision \
              --public-invites \
              --auto-accept-invites \
              --seed {{ $.Values.acapy.env.SEED }} \
              --auto-accept-requests \
              --auto-ping-connection \
              --auto-respond-credential-proposal \
              --auto-respond-credential-offer \
              --auto-respond-credential-request \
              --auto-respond-presentation-proposal \
              --auto-respond-presentation-request \
              --auto-store-credential \
              --auto-verify-presentation \
              --preserve-exchange-records \
              --invite-public \
              --requests-through-public-did \
              --log-level INFO
        ports:
          - containerPort: 5555
      - name: {{ .name }}
        image: {{ .image.name }}:{{ .image.tag | default $.Chart.AppVersion }}
        imagePullPolicy: {{ .image.pullPolicy }}
        securityContext:
            {{- toYaml .securityContext | nindent 12 }}
        ports:
        - containerPort: {{ .service.port }}
        command: ["./pcf"]
        args: ["-c", "../config/pcfcfg.yaml"]
        env:
          - name: GIN_MODE
            value: release
        volumeMounts:
        - mountPath: {{ .volume.mount }}
          name: {{ include "free5gc-pcf.fullname" $ }}-volume
        resources:
            {{- toYaml .resources | nindent 12 }}
      - name: controller
        image: "{{ $.Values.controller.image }}:{{ $.Values.controller.tag }}"
        ports:
        - containerPort: 9999
        env:
        - name: NF_TYPE
          value: "{{ $.Values.controller.env.NF_TYPE }}"
        - name: ISSUER_DID
          value: "{{ $.Values.controller.env.ISSUER_DID }}"
        - name: SCHEMA_ID
          value: "{{ $.Values.controller.env.SCHEMA_ID }}"
        - name: CRED_DEF_ID
          value: "{{ $.Values.controller.env.CRED_DEF_ID }}"
        - name: ACAPY_IP
          value: "{{ $.Values.controller.env.ACAPY_IP }}"
        - name: ACAPY_PORT
          value: "{{ $.Values.controller.env.ACAPY_PORT }}"
        - name: APP_PORT
          value: "{{ $.Values.controller.env.APP_PORT }}"
        - name: DB_PORT
          value: "{{ $.Values.controller.env.DB_PORT }}"
        - name: NF_PORT
          value: "{{ $.Values.controller.env.NF_PORT }}"
        - name: AMF_DID
          value: "{{ $.Values.controller.env.AMF_DID }}"
        - name: AUSF_DID
          value: "{{ $.Values.controller.env.AUSF_DID }}"
        - name: NRF_DID
          value: "{{ $.Values.controller.env.NRF_DID }}"
        - name: NSSF_DID
          value: "{{ $.Values.controller.env.NSSF_DID }}"
        - name: PCF_DID
          value: "{{ $.Values.controller.env.PCF_DID }}"
        - name: SMF_DID
          value: "{{ $.Values.controller.env.SMF_DID }}"
        - name: UDM_DID
          value: "{{ $.Values.controller.env.UDM_DID }}"
        - name: UDR_DID
          value: "{{ $.Values.controller.env.UDR_DID }}"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      nodeSelector:
        {{- toYaml .nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .affinity | nindent 8 }}
      tolerations:
        {{- toYaml .tolerations | nindent 8 }}

      volumes:
      - name: {{ include "free5gc-pcf.fullname" $ }}-volume
        projected:
          sources:
          - configMap:
              name: {{ include "free5gc-pcf.fullname" $ }}-configmap
{{- end }}
