{{- with .Values.nssf }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "free5gc-nssf.fullname" $ }}-acapy-service
  labels:
    {{- include "free5gc-nssf.labels" $ | nindent 4 }}
    project: {{ $.Values.global.projectName }}
    nf: {{ .name }}
spec:
  type: {{ $.Values.acapy.service.type }}
  ports:
    - port: {{ $.Values.acapy.service.port }}
      targetPort: 5555
      protocol: TCP
      name: http
  selector:
    {{- include "free5gc-nssf.selectorLabels" $ | nindent 4 }}
    project: {{ $.Values.global.projectName }}
    nf: {{ .name }}

{{- end }}
