{{- with .Values.asidecar }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "free5gc-ausf.fullname" $ }}-sidecar-service
  labels:
    {{- include "free5gc-ausf.labels" $ | nindent 4 }}
    project: {{ $.Values.global.projectName }}
    nf: {{ .name }}
spec:
  type: {{ .service.type }}
  ports:
    - port: {{ .service.port }}
      targetPort: {{ .service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "free5gc-ausf.selectorLabels" $ | nindent 4 }}
    project: {{ $.Values.global.projectName }}
    nf: {{ .name }}
{{- end }}
