apiVersion: v1
kind: Service
metadata:
  name: {{ include "free5gc-ausf.fullname" $ }}-sidecar-service
  labels:
    {{- include "free5gc-ausf.labels" $ | nindent 4 }}
    project: {{ $.Values.global.projectName }}
    nf: {{ .name }}
spec:
  type: NodePort
  ports:
    - port: 9999
      targetPort: 9999
      protocol: TCP
      name: http
  selector:
    {{- include "free5gc-ausf.selectorLabels" $ | nindent 4 }}
    project: {{ $.Values.global.projectName }}
    nf: {{ .name }}