#
# Software Name : free5gc-kubernetes
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at todo
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
# Default values for free5gcControlPlane chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

global:
  projectName: free5gc
  nrf:
    service:
      name: nrf-nnrf
      type: ClusterIP
      port: 80
      nodePort: "30800"
  sbi:
    scheme: http

initcontainers:
  curl:
    registry: towards5gs
    image: initcurl
    tag: "1.0.0"
  busybox:
    image: busybox
    tag: "1.32.0"

controller:
  name: controller
  image: haidinhtuan/controller
  tag: latest
  service:
    type: ClusterIP
    port: 9999
  env:
    NF_TYPE: ausf
    ISSUER_DID: "8G6ng6cn8iNnkU265MbGgJ"
    SCHEMA_ID: "8G6ng6cn8iNnkU265MbGgJ:2:auth:1.0"
    CRED_DEF_ID: "8G6ng6cn8iNnkU265MbGgJ:3:CL:55507:default"
    ACAPY_IP: "127.0.0.1"
    ACAPY_PORT: 7777
    APP_PORT: 9999
    DB_PORT: 5432
    NF_PORT: 80
    AMF_DID: "XttS63fu9n3NtKgQKDxwGi"
    AUSF_DID: "R4XrH8yGdYsVJt2mZZ5PbT"
    NRF_DID: "y77ZersNcdw9QaT2Jwucv"
    NSSF_DID: "4iQ373D2PMBPPFenwKU7GQ"
    PCF_DID: "NnG1VLYrsUC7aW2qvkuDZE"
    SMF_DID: "VK4N2U7aEToneqAu7bGSqp"
    UDM_DID: "Lq757Qm8wH4eHvcPY8yjfK"
    UDR_DID: "UGCCvUZwjKvmK3yzBCN36g"


database:
  name: database
  image: haidinhtuan/nf-db
  env:
    POSTGRES_PASSWORD: "postgres"

acapy:
  name: acapy
  image: bcgovimages/aries-cloudagent:py36-1.16-1_0.8.1
  env:
    ACAPY_ADMIN_INSECURE_MODE: "true"
    ACAPY_AUTO_PROVISION: "true"
    ACAPY_DEBUG_CONNECTIONS: "true"
    ACAPY_ENDPOINT: "http://free5gc-core-free5gc-ausf-acapy-service:5555"
    ACAPY_LABEL: "AUSF"
    ACAPY_LOG_LEVEL: "info"
    ACAPY_GENESIS_URL: "https://raw.githubusercontent.com/IDunion/indy-did-networks/refs/heads/main/networks/idunion/pool_transactions_genesis.json"
    ADMIN_PORT: "7777"
    AGENT_PORT: "5555"
    SEED: "lueKevd226eTGVKAV8zvJUvynCSyHZCJ"
    ACAPY_UNIVERSAL_RESOLVER: "https://dev.uniresolver.io/1.0/identifiers/"
  service: 
    type: ClusterIP
    port: 5555

ausf:
  name: ausf
  replicaCount: 1
  image:
    name: haidinhtuan/free5gc-ausf
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 80
  volume:
    mount: /free5gc/config/
  podAnnotations: {}
    # additional annotations
  imagePullSecrets: []
  podSecurityContext: {}
  securityContext: {}
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  readinessProbe:
    initialDelaySeconds: 0
    periodSeconds: 1
    timeoutSeconds: 1
    failureThreshold:  40
    successThreshold: 1
  livenessProbe:
    initialDelaySeconds: 120
    periodSeconds: 10
    timeoutSeconds: 10
    failureThreshold: 3
    successThreshold: 1
  nodeSelector: {}
  tolerations: []
  affinity: {}
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80
  ingress:
    enabled: false
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: chart-example.local
        paths: []
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local
  configuration:
    serviceNameList: |-
      - nausf-auth
    configuration: |-
      plmnSupportList:
        - mcc: 208
          mnc: 93
        - mcc: 123
          mnc: 45
      groupId: ausfGroup001
      eapAkaSupiImsiPrefix: false
    # the kind of log output
      # debugLevel: how detailed to output, value: trace, debug, info, warn, error, fatal, panic
      # ReportCaller: enable the caller report or not, value: true or false
    logger:
      AUSF:
        debugLevel: info
        ReportCaller: false
hostAliases:
  - ip: "127.0.0.1"
    hostnames:
    - "amf.snet.tuberlin"
    - "nssf.snet.tuberlin"
    - "pcf.snet.tuberlin"
    - "smf.snet.tuberlin"
    - "udm.snet.tuberlin"
    - "udr.snet.tuberlin"
    - "upf.snet.tuberlin"
