#
# Software Name : free5gc-kubernetes
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at todo
# or see the "LICENSE" file for more details.
#
# Author Hai Dinh-Tuan
# Software description: Helm charts to deploy free5GC core components and UE + RAN on top of Kubernetes
#
# Default values for free5gc-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  name: free5gc
  env:
    ISSUER_DID: ISSUER_DID
    SCHEMA_ID: SCHEMA_DID
    CRED_DEF_ID: CRED_DEF_ID
  userPlaneArchitecture: single  # possible values are "single" and "ulcl"
  nrf:
    service:
      name: nrf-nnrf
      type: ClusterIP
      port: 80
      nodePort: "30800"
  sbi:
    scheme: http
  amf:
    n2if:  # NGAP
      ipAddress: 10.100.50.249
    service:
      ngap:
        enabled: false
        name: amf-n2
        port: 38412
        nodeport: 31412
        protocol: SCTP
        type: NodePort
  smf:
    n4if:
      ipAddress: 10.100.50.244
  #Global network parametes
  n2network:
    enabled: true
    name: n2network
    type: macvlan
    masterIf: eth0
    subnetIP: 10.100.50.248
    cidr: 29
    gatewayIP: 10.100.50.254
    excludeIP: 10.100.50.254
  n3network:
    enabled: true
    name: n3network
    type: macvlan
    masterIf: eth0
    subnetIP: 10.100.50.232
    cidr: 29
    gatewayIP: 10.100.50.238
    excludeIP: 10.100.50.238
  n4network:
    enabled: true
    name: n4network
    type: macvlan
    masterIf: eth0
    subnetIP: 10.100.50.240
    cidr: 29
    gatewayIP: 10.100.50.246
    excludeIP: 10.100.50.246
  n6network:
    enabled: true
    name: n6network
    type: macvlan
    masterIf: eth1
    subnetIP: 10.100.100.0
    cidr: 24
    gatewayIP: 10.100.100.1
    excludeIP: 10.100.100.254
  n9network:
    enabled: true
    name: n9network
    type: macvlan
    masterIf: eth0
    subnetIP: 10.100.50.224
    cidr: 29
    gatewayIP: 10.100.50.230
    excludeIP: 10.100.50.230

# These parameters can be used to enable/disable deployment of subcharts
deployMongoDb: true
deployAmf: true
deployAusf: false
deployN3iwf: false
deployNrf: true
deployNssf: false
deployPcf: false
deploySmf: false
deployUdm: false
deployUdr: false
deployUpf: false
deployWebui: true
deployDbPython: true

# Disable the deployment of mongodb as an NRF subchart
free5gc-nrf:
  db:
    enabled: false

# This section can be used to override the default values in the MongoDB chart
mongodb:
  fullnameOverride: "mongodb"
  useStatefulSet: false
  auth:
    enabled: false
  persistence:
    size: 3Gi
    mountPath: /bitnami/mongodb/data/db/
  service:
    name: mongodb
    type: ClusterIP
    port: 27017
    nodePort: "30017"
