#
# Software Name : free5gc-kubernetes
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at todo
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
# Default values for free5gcControlPlane chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

global:
  projectName: free5gc
  nrf:
    service:
      name: nrf-nnrf
      type: ClusterIP
      port: 80
      nodePort: "30800"
  sbi:
    scheme: http

initcontainers:
  curl:
    registry: towards5gs
    image: initcurl
    tag: "1.0.0"
  busybox:
    image: busybox
    tag: "1.32.0"

db:
  enabled: false
# This section can be used to override the default values in the MongoDB chart (remember MongoDB is a subchart of the free5gcControlplane chart since control plane NFs rely on it.
mongodb:
  service:
    name: mongodb
    type: ClusterIP
    port: 27017
    nodePort: "30017"

controller:
  name: controller
  image: haidinhtuan/controller
  tag: latest
  service:
    type: ClusterIP
    port: 9999
  env:
    NF_TYPE: udr
    ISSUER_DID: "8G6ng6cn8iNnkU265MbGgJ"
    SCHEMA_ID: "8G6ng6cn8iNnkU265MbGgJ:2:auth:1.0"
    CRED_DEF_ID: "8G6ng6cn8iNnkU265MbGgJ:3:CL:55507:default"
    ACAPY_IP: "127.0.0.1"
    ACAPY_PORT: 7777
    APP_PORT: 9999
    DB_PORT: 5432
    NF_PORT: 80
    AMF_DID: "XttS63fu9n3NtKgQKDxwGi"
    AUSF_DID: "R4XrH8yGdYsVJt2mZZ5PbT"
    NRF_DID: "y77ZersNcdw9QaT2Jwucv"
    NSSF_DID: "4iQ373D2PMBPPFenwKU7GQ"
    PCF_DID: "NnG1VLYrsUC7aW2qvkuDZE"
    SMF_DID: "VK4N2U7aEToneqAu7bGSqp"
    UDM_DID: "Lq757Qm8wH4eHvcPY8yjfK"
    UDR_DID: "UGCCvUZwjKvmK3yzBCN36g"


database:
  name: database
  image: haidinhtuan/nf-db
  env:
    POSTGRES_PASSWORD: "postgres"

acapy:
  name: acapy
  image: bcgovimages/aries-cloudagent:py36-1.16-1_0.8.1
  env:
    ACAPY_ADMIN_INSECURE_MODE: "true"
    ACAPY_AUTO_PROVISION: "true"
    ACAPY_DEBUG_CONNECTIONS: "true"
    ACAPY_ENDPOINT: "http://free5gc-core-free5gc-udr-acapy-service:5555"
    ACAPY_LABEL: "UDR"
    ACAPY_LOG_LEVEL: "info"
    ACAPY_GENESIS_URL: "https://raw.githubusercontent.com/IDunion/indy-did-networks/refs/heads/main/networks/idunion/pool_transactions_genesis.json"
    ADMIN_PORT: "7777"
    AGENT_PORT: "5555"
    SEED: "AtWQaCeidmgladhXsQuSeX2x8nXxzGdL"
  service: 
    type: ClusterIP
    port: 5555

udr:
  name: udr
  replicaCount: 1
  image:
    name: haidinhtuan/free5gc-udr
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 80
  volume:
    mount: /free5gc/config/
  podAnnotations: {}
    # additional annotations
  imagePullSecrets: []
  podSecurityContext: {}
  securityContext: {}
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  readinessProbe:
    initialDelaySeconds: 0
    periodSeconds: 1
    timeoutSeconds: 1
    failureThreshold:  40
    successThreshold: 1
  livenessProbe:
    initialDelaySeconds: 120
    periodSeconds: 10
    timeoutSeconds: 10
    failureThreshold: 3
    successThreshold: 1
  nodeSelector: {}
  tolerations: []
  affinity: {}
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80
  ingress:
    enabled: false
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: chart-example.local
        paths: []
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local
  configuration:
    serviceNameList: |-


    configuration: |-


    # the kind of log output
      # debugLevel: how detailed to output, value: trace, debug, info, warn, error, fatal, panic
      # ReportCaller: enable the caller report or not, value: true or false
    logger:
      UDR:
        debugLevel: info
        ReportCaller: false
      MongoDBLibrary:
        debugLevel: info
        ReportCaller: false
      PathUtil:
        debugLevel: info
        ReportCaller: false
      OpenApi:
        debugLevel: info
        ReportCaller: false

free5gc:
  configmap:
    create: true
    name: free5gc4udr-configmap
  configuration:
    #all logging levels
    #panic
    #fatal
    #error
    #warn
    #info
    #debug
    #trace
    logger:
      UDR:
        debugLevel: info
        ReportCaller: true

hostAliases:
  - ip: "127.0.0.1"
    hostnames:
    - "ausf.snet.tuberlin"
    - "nssf.snet.tuberlin"
    - "pcf.snet.tuberlin"
    - "smf.snet.tuberlin"
    - "udm.snet.tuberlin"
    - "amf.snet.tuberlin"
    - "upf.snet.tuberlin"
